// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Helper$WildCards from "./Helper.bs.js";

function make(tokenId) {
  if (Helper$WildCards.isStringInteger(tokenId)) {
    return tokenId;
  }
  
}

function makeWithDefault(tokenId, $$default) {
  var id = make(tokenId);
  if (id !== undefined) {
    return id;
  } else {
    return String($$default);
  }
}

function makeFromInt(tokenId) {
  return String(tokenId);
}

export {
  make ,
  makeWithDefault ,
  makeFromInt ,
  
}
/* No side effect */
