// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactApollo from "react-apollo";
import * as Client$WildCards from "./Client.bs.js";
import * as ReactHooks from "@apollo/react-hooks";
import * as RootProvider$WildCards from "./RootProvider.bs.js";
import * as QlStateManager$WildCards from "./QlStateManager.bs.js";

function WildcardsProvider(Props) {
  var graphEndpoint = Props.graphEndpoint;
  var children = Props.children;
  var stewardContractAddress = Props.stewardContractAddress;
  var stewardAbi = Props.stewardAbi;
  var client = React.useMemo((function () {
          return Client$WildCards.instance(graphEndpoint);
        }), [graphEndpoint]);
  return React.createElement(RootProvider$WildCards.make, {
              children: React.createElement(ReactApollo.ApolloProvider, {
                    client: client,
                    children: React.createElement(ReactHooks.ApolloProvider, {
                          client: client,
                          children: React.createElement(QlStateManager$WildCards.make, {
                                children: children
                              })
                        })
                  }),
              stewardContractAddress: stewardContractAddress,
              stewardAbi: stewardAbi
            });
}

var make = WildcardsProvider;

export {
  make ,
  
}
/* react Not a pure module */
