// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Globals$WildCards from "./lib/Globals.bs.js";
import * as ProfileIcon$WildCards from "./lib/ProfileIcon.bs.js";
import * as Web3Connect$WildCards from "./lib/Web3Connect.bs.js";

function App(Props) {
  return React.createElement("div", undefined, React.createElement("h3", undefined, Globals$WildCards.restr("Connection Button:")), React.createElement(Web3Connect$WildCards.make, { }), React.createElement(Web3Connect$WildCards.Modal.make, { }), React.createElement("h3", undefined, Globals$WildCards.restr("Profile Icon:")), React.createElement(ProfileIcon$WildCards.make, { }), React.createElement("h2", undefined, Globals$WildCards.restr("Some react!")));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
