// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Buy$WildCards from "./harberger-lib/components/Buy.bs.js";
import * as Info$WildCards from "./harberger-lib/components/Info.bs.js";
import * as Globals$WildCards from "./harberger-lib/Globals.bs.js";
import * as TokenId$WildCards from "./harberger-lib/TokenId.bs.js";
import * as ProfileIcon$WildCards from "./harberger-lib/ProfileIcon.bs.js";
import * as UpdatePrice$WildCards from "./harberger-lib/components/UpdatePrice.bs.js";
import * as Web3Connect$WildCards from "./harberger-lib/Web3Connect.bs.js";
import * as UpdateDeposit$WildCards from "./harberger-lib/components/UpdateDeposit.bs.js";

function App(Props) {
  return React.createElement("div", undefined, React.createElement("h3", undefined, Globals$WildCards.restr("Connection Button:")), React.createElement(Web3Connect$WildCards.make, { }), React.createElement(Web3Connect$WildCards.Modal.make, { }), React.createElement("h3", undefined, Globals$WildCards.restr("Profile Icon:")), React.createElement(ProfileIcon$WildCards.make, { }), React.createElement("h3", undefined, Globals$WildCards.restr("Token Info:")), React.createElement(Info$WildCards.make, {
                  tokenId: TokenId$WildCards.makeFromInt(0)
                }), React.createElement("h3", undefined, Globals$WildCards.restr("Buy this token:")), React.createElement(Buy$WildCards.make, {
                  tokenId: TokenId$WildCards.makeFromInt(0)
                }), React.createElement("h3", undefined, Globals$WildCards.restr("Change price")), React.createElement(UpdatePrice$WildCards.make, {
                  tokenId: TokenId$WildCards.makeFromInt(0)
                }), React.createElement("h3", undefined, Globals$WildCards.restr("Update Deposit")), React.createElement(UpdateDeposit$WildCards.make, { }), React.createElement("h2", undefined, Globals$WildCards.restr("Some react!")));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
